### ISSUE TITLE
brace-expansion: lift to 1.1.18 / 5.0.9 once they clear the 24h minimumReleaseAge gate

### ISSUE THREAD

**Issue by sweetrb** [sweetrb/apple-mail-mcp#121]
#119 moved the dev-only `brace-expansion@1` path (ESLint → `minimatch@3.1.5`) onto `1.1.17`, the upstream v1 backport for **GHSA-mh99-v99m-4gvg / CVE-2026-14257**. That fix is **incomplete on both lines**, and the completions landed the same morning #119 was reviewed.

## What 1.1.17 / 5.0.8 missed

`1.1.17` added `EXPANSION_MAX_LENGTH` to bound the accumulator in `combine`, but did **not** thread `maxLength` into `expandSequence` — so the sequence path (`{1..N}`, `{a..z..k}`) stayed uncapped in total output length, which is the same unbounded-memory shape the CVE describes.

`1.1.18` (published 2026-07-30T10:17Z) fixes it:

```js
-function expandSequence(body, isAlphaSequence, max)
+function expandSequence(body, isAlphaSequence, max, maxLength)
...
+    if (length + c.length > maxLength) break
     N.push(c)
+    length += c.length
```

plus bounding the `values` accumulation and correcting `max` accounting for dropped empties.

`5.0.9` (published 2026-07-30T10:00Z) is the **same change** on the v5 line — verified by diffing the two tarballs. So this repo's *other* path, `minimatch@10.2.6 → brace-expansion@5.0.8`, is also on the incomplete fix today.

## Why this was not just folded into #119

`minimumReleaseAge: 1440` (24h). Both releases were ~1 hour old at review time, and `brace-expansion` is a high-value supply-chain target — adding a `minimumReleaseAgeExclude` carve-out to pull a one-hour-old release is exactly the case the gate exists to prevent. Waiting costs nothing real here: the advisory is **dev-toolchain-only** (`brace-expansion` does not appear in `build/index.js`), and reaching it requires feeding adversarial brace input to a lint run.

## To do (from 2026-07-31 ~10:17Z, when both clear the gate)

- [ ] `pnpm-workspace.yaml`: `brace-expansion@<1.1.18: 1.1.18` (replacing the `<1.1.17: 1.1.17` override)
- [ ] Lift the v5 path to `5.0.9` — confirm whether `minimatch@10.2.6`'s range picks it up on a plain re-resolve, or whether it needs its own floor
- [ ] Re-resolve the lockfile with **no** `minimumReleaseAgeExclude` entry, and confirm `pnpm install --lockfile-only` reports "Lockfile passes supply-chain policies"
- [ ] Confirm `build/` stays byte-identical (dev-only ⇒ no version bump), and CHANGELOG the supersession
- [ ] Same pass in the three sibling repos if they resolve `brace-expansion` on either line

Note GitHub's advisory metadata still lists `5.0.8` as the patched version (last updated 2026-07-24), so `pnpm audit` output is not a reliable signal here — compare the published tarballs.

Follow-up to #119 (thanks @jjoanna2-debug).

**Comment by sweetrb** [comment]
Independent verification ahead of the gate clearing, so tomorrow's lift is based on checked evidence rather than the advisory text.

## The code-level finding is confirmed

Diffed the published tarballs locally. Both lines make the identical change, and it is exactly the gap identified when #119 was merged — `expandSequence` was never given the length bound:

```diff
-function expandSequence(body, isAlphaSequence, max)
+function expandSequence(body, isAlphaSequence, max, maxLength)
@@
+  let length = 0
   for (let i = x; test(i, y) && N.length < max; i += incr) {
     ...
+    if (length + c.length > maxLength) break
     N.push(c)
+    length += c.length
   }
@@
-  values = expandSequence(m.body, isAlphaSequence, max)
+  values = expandSequence(m.body, isAlphaSequence, max, maxLength)
```

So `1.1.17` and `5.0.8` do bound `combine`, but the sequence path builds its array with only the **count** bound (`N.length < max`) and no character bound. `1.1.18` / `5.0.9` add it. The two lines are the same change, which supports treating them as one lift.

## What I measured, and what I could not

Worth recording honestly, because it changes how the fix should be described.

`EXPANSION_MAX` caps results at **100,000** and `EXPANSION_MAX_LENGTH` at **4,000,000** characters. The count bound therefore binds first unless individual items exceed ~40 characters — with ordinary padding both versions behave identically:

```
{000001..100000}        1.1.17: 100000 results, 37ms    1.1.18: 100000 results, 33ms
{00000001..10000000}    1.1.17: 100000 results, 33ms    1.1.18: 100000 results, 33ms
```

Forcing 60-character padding so the length bound is the binding one:

```
{0…01..100000}          1.1.17: 66666 results, 64ms, 138MB RSS
                        1.1.18: 66666 results, 48ms, 106MB RSS
```

Both truncate at the same 3,999,960 characters, with `1.1.17` using ~30% more resident memory to get there — consistent with it materialising more of the sequence before the outer bound truncates.

**I was not able to reproduce the ~565× timing and ~3× memory magnitudes reported on #119** (`1.1.17` 5,088 ms / 171 MiB vs `1.1.18` 9 ms / 57 MiB) in any shape I tried. That does not contradict the fix — the missing bound is plainly there in the diff — but it does mean I can only vouch for the code-level defect and a modest measured overhead, not for that magnitude. If there is a harness that produces it, I would like to see it; there may be a shape (nested braces re-expanding the sequence, or a caller passing a large `max`) that I did not hit.

## Disposition unchanged

Lift both lines to `1.1.18` / `5.0.9` once the 24 h `minimumReleaseAge` clears. As of this comment `1.1.18` is 8.8 h old and `5.0.9` 9.1 h, so they clear at roughly 10:17Z and 10:00Z tomorrow — ahead of the 07:30 local scheduled run, which should pick this up without intervention. Dev-toolchain only; `brace-expansion` is not in the shipped bundle.

**Comment by jjoanna2-debug** [comment]
Found it: the omitted parameter in my earlier comment was the **pad width**. That run used 10,000 leading zeroes, not ordinary 60-character padding. With that input, the large timing/RSS delta reproduces because the incomplete versions materialise the full 100,000-value sequence before `combine` applies `maxLength`; the complete versions enforce `maxLength` inside `expandSequence`.

Exact harness:

```js
// repro.cjs
const { performance } = require('node:perf_hooks')
const loaded = require(process.argv[2])
const expand = typeof loaded === 'function' ? loaded : loaded.expand
const input = `{${'0'.repeat(10_000)}1..100000}`
const started = performance.now()
const output = expand(input)
console.log({
  results: output.length,
  chars: output.reduce((total, value) => total + value.length, 0),
  ms: Math.round(performance.now() - started),
})
```

Run each package under the same cap with:

```sh
/usr/bin/time -l node --max-old-space-size=64 repro.cjs /path/to/package/entrypoint
```

Fresh run on this machine (Node 26.5.0):

```
1.1.17  4606 ms  176,078,848 B max RSS
1.1.18     9 ms   60,997,632 B max RSS
5.0.8   4662 ms  176,078,848 B max RSS
5.0.9     16 ms   61,456,384 B max RSS
```

All four return the same bounded final result: 399 strings / 3,990,399 characters. The difference is intermediate work. The incomplete lines first construct up to 100,000 roughly 10 KB strings; the complete lines stop sequence construction as soon as the 4,000,000-character budget is reached.

So your 60-character measurement is correct for that width, and the earlier magnitude is also reproducible with the missing 10,000-character pad parameter. This does not change the disposition: the post-gate 1.1.18 / 5.0.9 lift remains the complete fix.

**Comment by sweetrb** [comment]
Closed by #123. Recording the outcome of the last checklist item, since it turned out to be the largest part of this.

**"Same pass in the three sibling repos"** — needed, and wider than this issue assumed. This repo resolves two `brace-expansion` majors; notes, numbers and photos each resolve **three**, because they still pull `minimatch@9` → the v2 line, which mail doesn't have. Two of their four resolved paths were below even the advisory's own floor:

| line | mail (before #123) | siblings (before) | now |
|---|---|---|---|
| v1 | `1.1.17` | `1.1.16` — **unpatched** | `1.1.18` |
| v2 | — | `2.1.2`/`2.1.3` | `2.1.4` |
| v5 | `5.0.8` | `5.0.7` — **unpatched** + `5.0.8` | `5.0.9` |

`2.1.4` is the v2 line's complete fix, published 2026-07-30T10:15Z — same change, same day as `1.1.18`/`5.0.9`, and it cleared the same 24 h gate. Ported in sweetrb/apple-notes-mcp#113, sweetrb/apple-numbers-mcp#49, sweetrb/apple-photos-mcp#60.

**Two corrections to how this issue framed the fix**, so the record is accurate:

1. The plan said "confirm whether `minimatch@10.2.6`'s range picks \[5.0.9\] up on a plain re-resolve, or whether it needs its own floor." It did pick it up — but re-resolution isn't a floor. `brace-expansion@<1.1.18` doesn't match `5.0.8` under semver, so nothing pinned the v5 result. Both majors now carry an explicit floor.

2. The floors must be **two-sided** (`>=5.0.0 <5.0.9`, not `<5.0.9`). A bare upper bound also matches `1.1.18` and `2.1.4` under semver, so it would force minimatch 3's CommonJS path onto the v5 ESM API — reintroducing the exact `expand is not a function` failure that made the v1 backport necessary in #119.

`pnpm audit` will keep reporting this everywhere until GitHub's metadata catches up; its `<= 5.0.7` range marks the whole v1 line vulnerable under semver, so it can't distinguish `1.1.16` from `1.1.18`. The lockfile `overrides:` section is the check that actually means something.
